version: '3'

services:
  db:
    image: mysql:latest
    container_name: db-java-app
    environment:
      MYSQL_ROOT_PASSWORD: training-2023
      MYSQL_DATABASE: users
      MYSQL_USER: training
      MYSQL_PASSWORD: training_pw
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: unless-stopped
    ports:
      - "3307:3307"
    networks:
      - app-network

  app:
    image: 29trxngxx/java-app-demo:{tag}
    ports:
      - "8001:8081"
    environment:
      DB_HOST: db
      DB_USER: training
      DB_PASSWORD: training_pw
      DB_DATABASE: users
      BUILD_ENV: stage
    networks:
      - app-network

networks:
  app-network:
    external: true
